# Generated by Django 4.2.3 on 2023-08-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_product_image_alter_product_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image2',
            field=models.FileField(blank=True, upload_to='Photos', verbose_name='resm2'),
        ),
    ]
