# Generated by Django 4.2.3 on 2023-08-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product_product_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image2',
            field=models.FileField(blank=True, default='deneme1.jpeg', upload_to='Photos', verbose_name='resm2'),
        ),
    ]
