# Generated by Django 4.2.3 on 2023-08-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_navcover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image2',
            field=models.FileField(blank=True, null=True, upload_to='Photos', verbose_name='resm2'),
        ),
    ]
