# Generated by Django 4.2.3 on 2023-08-25 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_product_product_image2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NavCover',
        ),
    ]
