# Generated by Django 4.2.3 on 2023-08-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_linkedin',
            field=models.URLField(verbose_name='linkedin'),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_site',
            field=models.URLField(verbose_name='site'),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_x',
            field=models.URLField(verbose_name='x'),
        ),
    ]
