# Generated by Django 4.2.3 on 2023-08-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_employee_employee_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=50, verbose_name='title')),
                ('service_content', models.CharField(max_length=50, verbose_name='content')),
                ('service_image', models.FileField(upload_to='Photos', verbose_name='image')),
            ],
        ),
    ]
