# Generated by Django 4.2.3 on 2023-08-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_content',
            field=models.CharField(blank=True, max_length=50, verbose_name='content'),
        ),
    ]
