# Generated by Django 4.2.3 on 2023-08-31 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0015_alter_services_service_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_message', models.TextField(verbose_name='mesaji')),
                ('comment_date', models.DateField(auto_now_add=True, verbose_name='yorum_saati')),
                ('comment_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='userin_fotosu')),
                ('comment_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='k_adi', to=settings.AUTH_USER_MODEL, verbose_name='kullanıcı_adi')),
            ],
        ),
    ]
