# Generated by Django 4.2.3 on 2023-08-31 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_image',
            field=models.FileField(upload_to='comment_Photo', verbose_name='foto'),
        ),
    ]
