# Generated by Django 4.2.3 on 2023-08-31 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_comment_comment_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_username',
            new_name='comment_user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_image',
        ),
    ]
