# Generated by Django 4.2.3 on 2023-09-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_comment_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explore_content1', models.CharField(max_length=50, verbose_name='content1')),
                ('explore_content2', models.CharField(max_length=50, verbose_name='content2')),
                ('explore_content3', models.CharField(max_length=50, verbose_name='content3')),
                ('explore_content4', models.CharField(max_length=50, verbose_name='content4')),
                ('explore_title', models.CharField(max_length=50, verbose_name='title')),
                ('explore_title2', models.CharField(max_length=50, verbose_name='title2')),
                ('image', models.FileField(upload_to=None, verbose_name='image')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_message',
            field=models.TextField(verbose_name=()),
        ),
    ]
