# Generated by Django 4.2.3 on 2023-09-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_explore_explore_content1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='explore',
            name='explore_first_title',
            field=models.CharField(max_length=50, null=True, verbose_name='title_first'),
        ),
    ]
