# Generated by Django 4.2.3 on 2023-09-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_explore_explore_first_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explore',
            name='explore_content1',
            field=models.TextField(blank=True, max_length=50, verbose_name='content1'),
        ),
        migrations.AlterField(
            model_name='explore',
            name='explore_content2',
            field=models.TextField(blank=True, max_length=50, verbose_name='content2'),
        ),
        migrations.AlterField(
            model_name='explore',
            name='explore_content3',
            field=models.TextField(blank=True, max_length=50, verbose_name='content3'),
        ),
        migrations.AlterField(
            model_name='explore',
            name='explore_content4',
            field=models.TextField(blank=True, max_length=50, verbose_name='content4'),
        ),
        migrations.AlterField(
            model_name='explore',
            name='explore_first_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='title_first'),
        ),
        migrations.AlterField(
            model_name='explore',
            name='explore_title',
            field=models.CharField(blank=True, max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='explore',
            name='explore_title2',
            field=models.CharField(blank=True, max_length=50, verbose_name='title2'),
        ),
        migrations.AlterField(
            model_name='explore',
            name='image',
            field=models.FileField(blank=True, upload_to='Explore', verbose_name='image'),
        ),
    ]
