# Generated by Django 4.2.3 on 2023-09-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_explore_explore_content1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='explore',
            name='explore_title3',
            field=models.CharField(blank=True, max_length=50, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='explore',
            name='explore_title4',
            field=models.CharField(blank=True, max_length=50, verbose_name='title2'),
        ),
        migrations.AddField(
            model_name='explore',
            name='image2',
            field=models.FileField(blank=True, upload_to='Explore', verbose_name='image'),
        ),
    ]
