# Generated by Django 4.2.3 on 2023-09-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_explore_image2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sosial_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sosial_link', models.URLField(verbose_name='https://www.instagram.com/')),
                ('sosial_title', models.CharField(max_length=50, verbose_name='title')),
                ('sosial_image', models.FileField(upload_to='Sosial', verbose_name='image')),
            ],
        ),
    ]
