# Generated by Django 4.2.3 on 2023-09-18 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_sosial_media_sosial_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explore_title', models.CharField(blank=True, max_length=50, verbose_name='title')),
                ('explore_title2', models.CharField(blank=True, max_length=50, verbose_name='title2')),
                ('image', models.FileField(blank=True, upload_to='Explore', verbose_name='image')),
            ],
        ),
        migrations.RemoveField(
            model_name='explore',
            name='explore_title',
        ),
        migrations.RemoveField(
            model_name='explore',
            name='explore_title2',
        ),
        migrations.RemoveField(
            model_name='explore',
            name='explore_title3',
        ),
        migrations.RemoveField(
            model_name='explore',
            name='explore_title4',
        ),
        migrations.RemoveField(
            model_name='explore',
            name='image',
        ),
        migrations.RemoveField(
            model_name='explore',
            name='image2',
        ),
        migrations.AddField(
            model_name='explore',
            name='baglanti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.expproduct', verbose_name='bağlanti'),
        ),
    ]
