# Generated by Django 4.2.3 on 2023-09-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_expproduct_remove_explore_explore_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expproduct',
            name='explore_title',
        ),
        migrations.RemoveField(
            model_name='expproduct',
            name='explore_title2',
        ),
        migrations.RemoveField(
            model_name='expproduct',
            name='image',
        ),
        migrations.AddField(
            model_name='explore',
            name='explore_title',
            field=models.CharField(blank=True, max_length=50, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='explore',
            name='explore_title2',
            field=models.CharField(blank=True, max_length=50, verbose_name='title2'),
        ),
        migrations.AddField(
            model_name='explore',
            name='image',
            field=models.FileField(blank=True, upload_to='Explore', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='expproduct',
            name='connect_explore',
            field=models.CharField(blank=True, max_length=50, verbose_name='conn'),
        ),
    ]
